server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  msg: '"Welcome to spring boot"'